# Generated by Django 4.0.4 on 2022-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasbench101', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasbench101result',
            name='final_test_accuracy',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='nasbench101result',
            name='final_validation_accuracy',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='nasbench101result',
            name='flops',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='nasbench101result',
            name='params',
            field=models.FloatField(default=-1),
        ),
    ]
