# Generated by Django 4.0.4 on 2022-07-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasbench101', '0002_nasbench101result_final_test_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasbench101result',
            name='epoch108',
        ),
        migrations.RemoveField(
            model_name='nasbench101result',
            name='epoch12',
        ),
        migrations.RemoveField(
            model_name='nasbench101result',
            name='epoch36',
        ),
        migrations.RemoveField(
            model_name='nasbench101result',
            name='epoch4',
        ),
    ]
